services:
  loki:
    image: grafana/loki:3.7.0
    container_name: obs-lab-loki
    restart: unless-stopped

    command:
      - "-config.file=/etc/loki/loki.yml"

    ports:
      - "3100:3100"

    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/loki

  grafana:
    image: grafana/grafana:11.5.2
    container_name: obs-lab-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

    depends_on:
      - loki

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:3000/api/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  loki_data:
  grafana_data:
